
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { AxiosInterceptor } from "@/lib/api/Interceptor/interceptor";
import { Provider } from "@/util/Providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  AxiosInterceptor()

  return (
    <html lang="en">
      <body className={inter.className}>
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
            <main className="max-w-7xl mx-auto ">
              <Provider>
              {children}
              </Provider>
            </main>
          </ThemeProvider>

      </body>
    </html>
  );
}
